en:
  languageCode: en
  languageName: English
  contentDir: content/en

en:
  languageCode: es
  languageName: Español
  contentDir: content/es

# Uncomment for multilingual sites, and customize the following config.
# zh:
#   languageCode: zh
#   languageName: 简体中文
#   contentDir: content/zh
#   title: 中文标题