main:
  - name: About
    url: '#about'
    weight: 1

  - name: Posts
    url: /posts/
    weight: 2

  - name: Infographics
    url: /docs/
    weight: 3

  - name: About us   
    url: /authors/
    weight: 4

